### ISSUE TITLE
motion mask in kitti

### ISSUE THREAD

**Issue by Qianqian3764** [YihongSun/Dynamo-Depth#7]
thanks for your excellent job!
Using the weights provided on the official website to test on the kitti dataset, it is found that some moving objects are not successfully labeled, and the results are as follows:
![image](https://github.com/YihongSun/Dynamo-Depth/assets/10708893/fe78db6c-ea2f-4ebf-930e-95eb21901da5)
Is this normal on kitti dataset?

**Comment by YihongSun** [comment]
Thank you for your interest in our work!

That is expected. Due to a limited amount of moving objects in KITTI compared to Waymo and nuScenes, the independent motion network only has a few moving instances to learn from (in a way similar to limited positive examples in class imbalance datasets). 

Designing specific sampling strategies for training may mitigate the issue, but since the focus of the paper was on learning with many moving objects, we leave this for future work.

Feel free to reply if you have any other questions or concerns!

**Comment by Qianqian3764** [comment]
Thank you for your timely reply and for solving my confusion！
